name: daily-report

on:
  # schedule:
  #   - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
#       - name: Run email code
#         env:
#           USER_EMAIL: jujuaditya037@gmail.com
#           USER_PASSWORD: Aditya@039
#         run: python send_email.py
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3.1.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: jujuaditya037@gmail.com
          password: Aditya@039
          subject: 'GitHub Action Job Status: ${{ job.status }}'
          body: 'The job ${{ github.job }} has completed with ${{ job.status }} status.'
          to: jujuaditya037@gmail.com
          from: jujuaditya037@gmail.com
          content_type: text/plain   
